<?php
declare(strict_types=1);

namespace Xcore\Generator\Doctrine\ORM\Entity;

trait AutogeneratedIdsTrait
{
    /**
     * @var bool
     */
    private $autogeneratedIds = true;

    public function getAutogeneratedIds(): bool
    {
        return $this->autogeneratedIds;
    }

    public function setAutogeneratedIds(bool $autogeneratedIds): void
    {
        $this->autogeneratedIds = $autogeneratedIds;
    }
}
